<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Course Report</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #333; }
        h1 { font-size: 20px; color: #667eea; text-align: center; margin-bottom: 5px; }
        h2 { font-size: 14px; color: #666; text-align: center; margin-top: 0; font-weight: normal; }
        .meta { text-align: center; font-size: 9px; color: #999; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th { background: #667eea; color: #fff; padding: 8px 6px; text-align: left; font-size: 9px; }
        td { padding: 6px; border-bottom: 1px solid #eee; font-size: 9px; }
        tr:nth-child(even) { background: #f8f9fa; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 8px; color: #999; padding: 10px 0; border-top: 1px solid #eee; }
        .badge { display: inline-block; padding: 2px 6px; border-radius: 3px; font-size: 8px; }
        .badge-success { background: #d4edda; color: #155724; }
        .badge-warning { background: #fff3cd; color: #856404; }
        .summary { margin-bottom: 15px; }
        .summary-item { display: inline-block; margin-right: 20px; font-size: 10px; }
        .summary-item strong { color: #667eea; }
    </style>
</head>
<body>
    <h1>Course Analytics Report</h1>
    <h2>E-Learning Management System</h2>
    <div class="meta">Generated on: {{ now()->format('F d, Y \\a\\t H:i') }}</div>

    <div class="summary">
        <span class="summary-item">Total Courses: <strong>{{ count($courses) }}</strong></span>
        <span class="summary-item">Generated by: <strong>{{ auth()->user()->name }}</strong></span>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Course</th>
                <th>Instructor</th>
                <th>Category</th>
                <th>Level</th>
                <th>Status</th>
                <th>Students</th>
                <th>Completed</th>
                <th>Completion %</th>
            </tr>
        </thead>
        <tbody>
            @foreach($courses as $index => $course)
                @php
                    $totalStudents = $course->enrollments->count();
                    $completedStudents = $course->enrollments->where('status', 'completed')->count();
                    $completionRate = $totalStudents > 0 ? round(($completedStudents / $totalStudents) * 100, 1) : 0;
                @endphp
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $course->title }}</td>
                    <td>{{ $course->instructor->name ?? 'N/A' }}</td>
                    <td>{{ $course->category->category_name ?? 'N/A' }}</td>
                    <td><span class="badge badge-success">{{ ucfirst($course->level) }}</span></td>
                    <td><span class="badge" style="background: {{ $course->status === 'published' ? '#d4edda' : '#fff3cd' }}; color: {{ $course->status === 'published' ? '#155724' : '#856404' }};">{{ ucfirst($course->status) }}</span></td>
                    <td>{{ $totalStudents }}</td>
                    <td>{{ $completedStudents }}</td>
                    <td>{{ $completionRate }}%</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        E-LMS Platform &copy; {{ date('Y') }} — This is a system-generated report
    </div>
</body>
</html>
